# Generated by Django 5.2.7 on 2025-11-19 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('personal', 'Personal'), ('vehiculo', 'Vehículo'), ('empresa', 'Empresa')], max_length=20)),
                ('obligatorio', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='MarcaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.TextField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('iestado', models.IntegerField(blank=True, default=1, null=True, verbose_name='Estado (1=Activo, 0=Inactivo)')),
                ('ialtafecha', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación')),
                ('ialtahora', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Hora de Creación')),
                ('imodificadofecha', models.DateField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('imodificadohora', models.DateTimeField(auto_now=True, null=True, verbose_name='Hora de Modificación')),
                ('icapturo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_capturadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Capturó')),
                ('imodifico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Último Usuario que Modificó')),
            ],
            options={
                'verbose_name': 'Marca de Vehículo',
                'verbose_name_plural': 'Marcas de Vehículos',
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Municipio')),
                ('id_estado', models.IntegerField(db_column='id_estado', verbose_name='ID de Estado')),
                ('iestado', models.IntegerField(default=1, verbose_name='Estado (1=Activo, 0=Inactivo)')),
                ('ialtafecha', models.DateField(db_column='ialtafecha', default=django.utils.timezone.now, verbose_name='Fecha de Alta')),
                ('ialtahora', models.TimeField(db_column='ialtahora', default=django.utils.timezone.now, verbose_name='Hora de Alta')),
                ('imodificadofecha', models.DateField(blank=True, db_column='imodificadofecha', null=True, verbose_name='Fecha de Modificación')),
                ('imodificadohora', models.TimeField(blank=True, db_column='imodificadohora', null=True, verbose_name='Hora de Modificación')),
                ('icapturo', models.ForeignKey(db_column='icapturo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Capturó')),
                ('imodifico', models.ForeignKey(blank=True, db_column='imodifico', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='municipios_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Modificó')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_concesion', models.CharField(max_length=50)),
                ('municipio_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='catalogo.marcavehiculo')),
            ],
            options={
                'verbose_name': 'Tipo de Vehículo',
                'verbose_name_plural': 'Tipos de Vehículos',
                'ordering': ['marca__marca', 'nombre'],
            },
        ),
    ]
