# Generated by Django 5.2.7 on 2025-11-19 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcavehiculo',
            name='ialtafecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='marcavehiculo',
            name='ialtahora',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='marcavehiculo',
            name='icapturo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_capturadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Capturó'),
        ),
        migrations.AlterField(
            model_name='marcavehiculo',
            name='iestado',
            field=models.IntegerField(default=1, verbose_name='Estado (1=Activo, 0=Inactivo)'),
        ),
        migrations.AlterField(
            model_name='marcavehiculo',
            name='imodificadofecha',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='marcavehiculo',
            name='imodificadohora',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='marcavehiculo',
            name='imodifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificó'),
        ),
        migrations.AlterField(
            model_name='marcavehiculo',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='Marca'),
        ),
    ]
