# Generated by Django 5.2.7 on 2025-11-19 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_marcavehiculo_ialtafecha_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaMoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=12)),
                ('regimen_fiscal', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Persona Moral',
                'verbose_name_plural': 'Personas Morales',
            },
        ),
        migrations.CreateModel(
            name='RepresentanteLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('regimen_fiscal', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_fijo', models.CharField(blank=True, max_length=15)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('persona_moral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representante', to='vehiculos.personamoral')),
            ],
            options={
                'verbose_name': 'Representante Legal',
                'verbose_name_plural': 'Representantes Legales',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=50, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('tipo_persona', models.CharField(choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral')], max_length=10)),
                ('clave_concesion', models.CharField(max_length=50)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('municipio_operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_de_vehiculos', to='catalogo.municipio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ['-creado'],
            },
        ),
        migrations.AddField(
            model_name='personamoral',
            name='solicitud',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_moral', to='vehiculos.solicitud'),
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100)),
                ('rfc', models.CharField(max_length=13)),
                ('regimen_fiscal', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono_fijo', models.CharField(blank=True, max_length=15)),
                ('telefono_movil', models.CharField(max_length=15)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona_fisica', to='vehiculos.solicitud')),
            ],
            options={
                'verbose_name': 'Persona Física',
                'verbose_name_plural': 'Personas Físicas',
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('titular', 'Domicilio del Titular'), ('fiscal', 'Domicilio Fiscal')], max_length=10)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=100)),
                ('colonia', models.CharField(max_length=100)),
                ('calle', models.CharField(max_length=200)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domicilios', to='vehiculos.solicitud')),
            ],
            options={
                'verbose_name': 'Domicilio',
                'verbose_name_plural': 'Domicilios',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano', models.IntegerField(help_text='Tamaño en bytes')),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipodocumento')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vehiculos.solicitud')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placas', models.CharField(blank=True, max_length=20)),
                ('numero_serie', models.CharField(blank=True, max_length=50)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.marcavehiculo')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculo', to='vehiculos.solicitud')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.tipovehiculo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
