# Generated by Django 5.2.7 on 2025-11-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personafisica',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
        migrations.AlterField(
            model_name='personafisica',
            name='rfc',
            field=models.CharField(max_length=13, unique=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='personamoral',
            name='rfc',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
